openapi: 3.0.1
info:
  title: Currency Convertor
  description: API for currency currency
  contact:
    name: Nosto Assessment
  version: latest
servers:
  - url: 'https://nostro-exchange.herokuapp.com'
    description: Production
  - url: 'http://localhost:8080'
tags:
  - name: currencies
    description: Currency Convertor
paths:

  /api/v1/currencies:
    get:
      summary: Get available currencies
      operationId: getCurrencies
      tags:
        - currencies
      responses:
        200:
          description: Available currencies obtained.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurrencyResponseDto'
        401:
          description: No valid API key provided.
        429:
          description: API request limit exceeded. See section Rate Limiting for more info.
        500:
          description: Target service have failed to process request.

  /api/v1/currencies/exchange:
    post:
      summary: Convert monetary value.
      operationId: convert
      tags:
        - currencies
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConvertRequestDto'
      responses:
        200:
          description: Currency successfully converted
          content:
            application/json:
              example: 0.837208
        400:
          description: The request was unacceptable, often due to missing a required parameter.
        401:
          description: No valid API key provided.
        429:
          description: API request limit exceeded. See section Rate Limiting for more info.
        500:
          description: Target service have failed to process request.

components:

  schemas:

    ConvertRequestDto:
      type: object
      required:
        - value
        - source
        - target
      properties:
        value:
          type: number
          description: 'A monetary value'
          example: 1.0
        source:
          type: string
          description: 'A source currency'
          example: 'EUR'
        target:
          type: string
          description: 'A target currency'
          example: 'GBP'

    CurrencyResponseDto:
      type: object
      properties:
        GBP:
          type: string
          example: 'British Pound Sterling'
        EUR:
          type: string
          example: 'Euro'
        USD:
          type: string
          example: 'United States Dollar'
